export const InstructionConsts = {
    'SWORD': "Third-Person Camera\n\nThis sword uses the third-person camera. \n\nThe third-person camera is enabled by default, and is good for building the relationship between the player and their avatar, and for showing off the avatar's actions, cosmetic items and wearables.\n\nThird-person camera can make it difficult for players to see small objects and text in front of them, and can be awkward in small spaces.",
    'GUN': "First-Person Camera\n\nThis blunderbuss uses the first-person camera.\n\nThe first-person camera is good for building the relationship between the player and the environment, for precise aiming and for seeing small objects and text in front of the player.\n\nFirst-person camera can make it difficult for players to see what is around them, and to avoid obstacles or jump over gaps.",
    'ORBIT': "Orbit Camera\n\nThis area triggers an orbit camera.\n\nThe orbit camera is good for showing off the environment, for giving players a sense of scale, traversing tricky terrain and taking selfies!\n\nOrbit camera can make it difficult for players to aim projectile weapons, see small objects and text in front of them, and can be awkward in small spaces.",
    'FIXED': "Fixed Camera\n\nThe fixed-camera decouples the player's camera from their avatar.\n\nThe fixed camera is good for giving player's an unencumbered view of the world. It's great for spectating, cut-scenes and for non-avatar focused gameplay.\n\nMake sure that players can easily return the camera to their avatar if they need to, and that they can't get stuck in the fixed camera.",
    'ATTACH': "Attach Camera\n\nPress the button to attach the camera to the moving block.\n\nThe attach camera target can be set to any entity or player in the world, including NPCs.\n\nUse the attach camera to enable players to inhabit a moving object, spectate another player or offer them an alternative perspective on the world.\n\n",
    'PAN': "Pan Camera\n\nThis area triggers a side-scrolling style camera movement, where the camera pans horizontally to reveal more of the environment.\n\nThe pan camera is good for enacting side-scrolling and top-down views that can be used to create a dynamic and engaging experience for your players.\n\nTry adjusting the vector position within the trigger properties to experiment with different view angles.",
    'ANGLES': "Pan Angles\n\nTry to input these positions into the property panel of a Pan Trigger.\n\nSide Scroll: (10, 0, 0)\nTop Down: (0, 10, 0)\n\n\nNote that negating any coordinate value will flip the camera to the opposite side.\n\nAdditionally, increasing or decreasing the value of the vector will move the camera closer to or further away from the player.",
    'FOLLOW': "Follow Camera\n\nThis area triggers a follow camera that tracks the player's movement.\n\nThe follow camera is good for creating a dynamic third-person perspective that maintains a consistent view of the player.\n\nYou can adjust properties like distance, rotation speed, and vertical offset to fine-tune the camera behavior. Consider enabling collision detection in tight spaces to prevent the camera from clipping through walls."
}
