/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
export namespace JSON_ShovelData {
    export const raw = `
[
    {
        "id": "shovel_base01",
        "name": "Wooden",
        "description": "Flimsy. Good at digging up garbage.",
        "icon": "1047304237206005",
        "index": "0",
        "price": "0",
        "levelRequirement": "1",
        "defaultLevel": "1",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_wooden02",
        "evolutionLevel": "49",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "No special ability.",
        "ability1AssetId": "1227152602536109",
        "shovelAsset": "1547013822931508"
    },
    {
        "id": "shovel_wooden02",
        "name": "Eldertree",
        "description": "Time and patience is always rewarded. ",
        "icon": "1280080493685632",
        "index": "1",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Life",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_base01",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows the discovery of The Tree of Life",
        "ability1AssetId": "1227152602536109",
        "shovelAsset": "1282725256895287"
    },
    {
        "id": "shovel_trusty",
        "name": "Trusty",
        "description": "Good for all the normal shoveling activities.",
        "icon": "1348107676389454",
        "index": "2",
        "price": "150",
        "levelRequirement": "2",
        "defaultLevel": "1",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "1600",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_trusty02",
        "evolutionLevel": "3",
        "baseShovel": "",
        "ability1Type": "gemCount",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.1",
        "ability1Description": "10% chance to Get 2x Gems for Streaks and Repeat Item digs",
        "ability1AssetId": "3884510811760801",
        "shovelAsset": "1435637331104949"
    },
    {
        "id": "shovel_trusty02",
        "name": "Trusty II",
        "description": "Good for all the normal shoveling activities.",
        "icon": "1034536978816950",
        "index": "3",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "4",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "7500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_trusty03",
        "evolutionLevel": "14",
        "baseShovel": "shovel_trusty",
        "ability1Type": "gemCount",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.2",
        "ability1Description": "20% chance to Get 2x Gems for Streaks and Repeat Item digs",
        "ability1AssetId": "3884510811760801",
        "shovelAsset": "1628834124478519"
    },
    {
        "id": "shovel_trusty03",
        "name": "Trusty III",
        "description": "Good for all the normal shoveling activities.",
        "icon": "1364250634625284",
        "index": "4",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "15",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "7500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_trusty04",
        "evolutionLevel": "29",
        "baseShovel": "shovel_trusty",
        "ability1Type": "gemCount",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.25",
        "ability1Description": "25% chance to Get 2x Gems for Streaks and Repeat Item digs",
        "ability1AssetId": "3884510811760801",
        "shovelAsset": "1045692104219360"
    },
    {
        "id": "shovel_trusty04",
        "name": "Trusty IV",
        "description": "Good for all the normal shoveling activities.",
        "icon": "1870669647050800",
        "index": "5",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "7500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_trusty",
        "ability1Type": "gemCount",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.35",
        "ability1Description": "35% chance to Get 2x Gems for Streaks and Repeat Item digs",
        "ability1AssetId": "3884510811760801",
        "shovelAsset": "724724197120785"
    },
    {
        "id": "shovel_pizza",
        "name": "Pizza",
        "description": "Mom told me not to play with my food. Look at me now.",
        "icon": "664217336533486",
        "index": "6",
        "price": "2800",
        "levelRequirement": "5",
        "defaultLevel": "1",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "1600",
        "categoryToBias": "Italian",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_pizza02",
        "evolutionLevel": "3",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Italian Items.",
        "ability1AssetId": "1428366711919556",
        "shovelAsset": "2283624082138674"
    },
    {
        "id": "shovel_pizza02",
        "name": "Pizza II",
        "description": "Mom told me not to play with my food. Look at me now.",
        "icon": "707701821846512",
        "index": "7",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "4",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "1600",
        "categoryToBias": "Italian",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_pizza03",
        "evolutionLevel": "14",
        "baseShovel": "shovel_pizza",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Italian Items.",
        "ability1AssetId": "1428366711919556",
        "shovelAsset": "1378717433219602"
    },
    {
        "id": "shovel_pizza03",
        "name": "Pizza III",
        "description": "Mom told me not to play with my food. Look at me now.",
        "icon": "1443888526768899",
        "index": "8",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "15",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "1600",
        "categoryToBias": "Italian",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_pizza04",
        "evolutionLevel": "29",
        "baseShovel": "shovel_pizza",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Italian Items.",
        "ability1AssetId": "1428366711919556",
        "shovelAsset": "779671044631199"
    },
    {
        "id": "shovel_pizza04",
        "name": "Pizza IV",
        "description": "Mom told me not to play with my food. Look at me now.",
        "icon": "1861640448017501",
        "index": "9",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "1600",
        "categoryToBias": "Italian",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_pizza",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Italian Items.",
        "ability1AssetId": "1428366711919556",
        "shovelAsset": "1287817479421980"
    },
    {
        "id": "shovel_aquatic",
        "name": "Aquatic",
        "description": "Rub a dub dub.",
        "icon": "2008250089649921",
        "index": "10",
        "price": "19500",
        "levelRequirement": "11",
        "defaultLevel": "10",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "9000",
        "categoryToBias": "Aquatic",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "starfish001",
        "itemCost1Amount": "1",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_aquatic02",
        "evolutionLevel": "14",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Aquatic Items.",
        "ability1AssetId": "1136546984638251",
        "shovelAsset": "2549910315349055"
    },
    {
        "id": "shovel_aquatic02",
        "name": "Aquatic II",
        "description": "Rub a dub dub.",
        "icon": "685309381078392",
        "index": "11",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "15",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "9000",
        "categoryToBias": "Aquatic",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_aquatic03",
        "evolutionLevel": "29",
        "baseShovel": "shovel_aquatic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Aquatic Items.",
        "ability1AssetId": "1136546984638251",
        "shovelAsset": "1315967116909837"
    },
    {
        "id": "shovel_aquatic03",
        "name": "Aquatic III",
        "description": "Rub a dub dub.",
        "icon": "2173159629779183",
        "index": "12",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "9000",
        "categoryToBias": "Aquatic",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_aquatic04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_aquatic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Aquatic Items.",
        "ability1AssetId": "1136546984638251",
        "shovelAsset": "1682035762508156"
    },
    {
        "id": "shovel_aquatic04",
        "name": "Aquatic IV",
        "description": "Rub a dub dub.",
        "icon": "1753471292211315",
        "index": "13",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "9000",
        "categoryToBias": "Aquatic",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_aquatic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Aquatic Items.",
        "ability1AssetId": "1136546984638251",
        "shovelAsset": "636572478924597"
    },
    {
        "id": "shovel_fortune",
        "name": "Toy",
        "description": "Digging with this shovel makes things feel larger than life!",
        "icon": "1621346525436772",
        "index": "14",
        "price": "21800",
        "levelRequirement": "13",
        "defaultLevel": "10",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_fortune02",
        "evolutionLevel": "24",
        "baseShovel": "",
        "ability1Type": "itemWeight",
        "ability1MinValue": "5",
        "ability1MaxValue": "5",
        "ability1Key": "",
        "ability1Chance": "0.1",
        "ability1Description": "10% chance to dig up items that are 5x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "1149591050328756"
    },
    {
        "id": "shovel_fortune02",
        "name": "Toy II",
        "description": "Digging with this shovel makes things feel larger than life!",
        "icon": "1228428615175804",
        "index": "15",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "25",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_fortune03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_fortune",
        "ability1Type": "itemWeight",
        "ability1MinValue": "5",
        "ability1MaxValue": "5",
        "ability1Key": "",
        "ability1Chance": "0.2",
        "ability1Description": "20% chance to dig up items that are 5x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "1719847348644455"
    },
    {
        "id": "shovel_fortune03",
        "name": "Toy III",
        "description": "Digging with this shovel makes things feel larger than life!",
        "icon": "1022917669828397",
        "index": "16",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_fortune04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_fortune",
        "ability1Type": "itemWeight",
        "ability1MinValue": "5",
        "ability1MaxValue": "5",
        "ability1Key": "",
        "ability1Chance": "0.25",
        "ability1Description": "25% chance to dig up items that are 5x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "2577026052649515"
    },
    {
        "id": "shovel_fortune04",
        "name": "Toy IV",
        "description": "Digging with this shovel makes things feel larger than life!",
        "icon": "722735590405717",
        "index": "17",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_fortune",
        "ability1Type": "itemWeight",
        "ability1MinValue": "5",
        "ability1MaxValue": "5",
        "ability1Key": "",
        "ability1Chance": "0.35",
        "ability1Description": "35% chance to dig up items that are 5x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "1270621754715804"
    },
    {
        "id": "shovel_jungle",
        "name": "Botanic",
        "description": "Leafy excellence.",
        "icon": "1719493992243062",
        "index": "18",
        "price": "23100",
        "levelRequirement": "16",
        "defaultLevel": "10",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "Botanic",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_jungle02",
        "evolutionLevel": "24",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Botanic Items.",
        "ability1AssetId": "3223666771125174",
        "shovelAsset": "632008549428503"
    },
    {
        "id": "shovel_jungle02",
        "name": "Botanic II",
        "description": "Leafy excellence.",
        "icon": "1217739356505705",
        "index": "19",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "25",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "Botanic",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_jungle03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_jungle",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Botanic Items.",
        "ability1AssetId": "3223666771125174",
        "shovelAsset": "696073360078887"
    },
    {
        "id": "shovel_jungle03",
        "name": "Botanic III",
        "description": "Leafy excellence.",
        "icon": "1406465874017593",
        "index": "20",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "Botanic",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_jungle04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_jungle",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Botanic Items.",
        "ability1AssetId": "3223666771125174",
        "shovelAsset": "771361662020804"
    },
    {
        "id": "shovel_jungle04",
        "name": "Botanic IV",
        "description": "Leafy excellence.",
        "icon": "3748452402119328",
        "index": "21",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "Botanic",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_jungle",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Botanic Items.",
        "ability1AssetId": "3223666771125174",
        "shovelAsset": "1120947516657359"
    },
    {
        "id": "shovel_skeleton",
        "name": "Skeleton",
        "description": "The spookiest Shovel around!",
        "icon": "1147981613499474",
        "index": "22",
        "price": "27900",
        "levelRequirement": "18",
        "defaultLevel": "18",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Fossil",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "skull001",
        "itemCost1Amount": "1",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_skeleton02",
        "evolutionLevel": "29",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Fossil Items.",
        "ability1AssetId": "640890491948404",
        "shovelAsset": "1820789675487371"
    },
    {
        "id": "shovel_skeleton02",
        "name": "Skeleton II",
        "description": "The spookiest Shovel around!",
        "icon": "729430786226093",
        "index": "23",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Fossil",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_skeleton03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_skeleton",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Fossil Items.",
        "ability1AssetId": "640890491948404",
        "shovelAsset": "728714846606603"
    },
    {
        "id": "shovel_skeleton03",
        "name": "Skeleton III",
        "description": "The spookiest Shovel around!",
        "icon": "1801799370381726",
        "index": "24",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Fossil",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_skeleton04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_skeleton",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Fossil Items.",
        "ability1AssetId": "640890491948404",
        "shovelAsset": "1308931894162861"
    },
    {
        "id": "shovel_skeleton04",
        "name": "Skeleton IV",
        "description": "The spookiest Shovel around!",
        "icon": "697311616085319",
        "index": "25",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Fossil",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_skeleton",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Fossil Items.",
        "ability1AssetId": "640890491948404",
        "shovelAsset": "2332253287168531"
    },
    {
        "id": "shovel_wisdom",
        "name": "Wisdom",
        "description": "With each dig the wielder becomes that much wiser.",
        "icon": "546999201818659",
        "index": "26",
        "price": "29300",
        "levelRequirement": "20",
        "defaultLevel": "20",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_wisdom02",
        "evolutionLevel": "29",
        "baseShovel": "",
        "ability1Type": "xpMod",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.2",
        "ability1Description": "20% chance to get 2x XP from digs.",
        "ability1AssetId": "1737845007137840",
        "shovelAsset": "1799274494030828"
    },
    {
        "id": "shovel_wisdom02",
        "name": "Wisdom II",
        "description": "With each dig the wielder becomes that much wiser.",
        "icon": "1728633544407988",
        "index": "27",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_wisdom03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_wisdom",
        "ability1Type": "xpMod",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.25",
        "ability1Description": "25% chance to Get 2x XP from digs.",
        "ability1AssetId": "1737845007137840",
        "shovelAsset": "3476478802484962"
    },
    {
        "id": "shovel_wisdom03",
        "name": "Wisdom III",
        "description": "With each dig the wielder becomes that much wiser.",
        "icon": "484159604754257",
        "index": "28",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_wisdom04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_wisdom",
        "ability1Type": "xpMod",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.35",
        "ability1Description": "35% chance to Get 2x XP from digs.",
        "ability1AssetId": "1737845007137840",
        "shovelAsset": "1808909880031578"
    },
    {
        "id": "shovel_wisdom04",
        "name": "Wisdom IV",
        "description": "With each dig the wielder becomes that much wiser.",
        "icon": "1241915941059473",
        "index": "29",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "2500",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_wisdom",
        "ability1Type": "xpMod",
        "ability1MinValue": "2",
        "ability1MaxValue": "2",
        "ability1Key": "",
        "ability1Chance": "0.5",
        "ability1Description": "50% chance to Get 2x XP from digs.",
        "ability1AssetId": "1737845007137840",
        "shovelAsset": "4322942531324849"
    },
    {
        "id": "shovel_icepop",
        "name": "Ice Pop",
        "description": "Ice Cream!",
        "icon": "1197443568685264",
        "index": "30",
        "price": "31400",
        "levelRequirement": "21",
        "defaultLevel": "20",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IcePop",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icepop02",
        "evolutionLevel": "29",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Ice Cream Items.",
        "ability1AssetId": "1699561200919782",
        "shovelAsset": "1046727063907776"
    },
    {
        "id": "shovel_icepop02",
        "name": "Ice Pop II",
        "description": "Ice Cream!",
        "icon": "1112718957625860",
        "index": "31",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IcePop",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icepop03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_icepop",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Ice Cream Items.",
        "ability1AssetId": "1699561200919782",
        "shovelAsset": "731038536349244"
    },
    {
        "id": "shovel_icepop03",
        "name": "Ice Pop III",
        "description": "Ice Cream!",
        "icon": "1939798486834743",
        "index": "32",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IcePop",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icepop04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_icepop",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Ice Cream Items.",
        "ability1AssetId": "1699561200919782",
        "shovelAsset": "1149271723699529"
    },
    {
        "id": "shovel_icepop04",
        "name": "Ice Pop IV",
        "description": "Ice Cream!",
        "icon": "1017249030577671",
        "index": "33",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IcePop",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_icepop",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Ice Cream Items.",
        "ability1AssetId": "1699561200919782",
        "shovelAsset": "25160456396876513"
    },
    {
        "id": "shovel_magic",
        "name": "Magical",
        "description": "Only a worthy Shoveler could pull this from the shrine.",
        "icon": "1152906806208204",
        "index": "34",
        "price": "34700",
        "levelRequirement": "24",
        "defaultLevel": "25",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Magical",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_magic02",
        "evolutionLevel": "34",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Magical Items.",
        "ability1AssetId": "594468267063917",
        "shovelAsset": "1337732397950737"
    },
    {
        "id": "shovel_magic02",
        "name": "Magical II",
        "description": "Only a worthy Shoveler could pull this from the shrine.",
        "icon": "1283069316678990",
        "index": "35",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "35",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Magical",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_magic03",
        "evolutionLevel": "44",
        "baseShovel": "shovel_magic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Magical Items.",
        "ability1AssetId": "594468267063917",
        "shovelAsset": "2824680494384611"
    },
    {
        "id": "shovel_magic03",
        "name": "Magical III",
        "description": "Only a worthy Shoveler could pull this from the shrine.",
        "icon": "1489235952250158",
        "index": "36",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "45",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Magical",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_magic04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_magic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Magical Items.",
        "ability1AssetId": "594468267063917",
        "shovelAsset": "1073577704879342"
    },
    {
        "id": "shovel_magic04",
        "name": "Magical IV",
        "description": "Only a worthy Shoveler could pull this from the shrine.",
        "icon": "1487127019402220",
        "index": "37",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Magical",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_magic",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Magical Items.",
        "ability1AssetId": "594468267063917",
        "shovelAsset": "757891193460232"
    },
    {
        "id": "shovel_creature",
        "name": "Creature",
        "description": "The greatest creatures of the islands will yield to you.",
        "icon": "901160525280656",
        "index": "38",
        "price": "40400",
        "levelRequirement": "30",
        "defaultLevel": "25",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Creature",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_creature02",
        "evolutionLevel": "34",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Creature Items.",
        "ability1AssetId": "1848598249035764",
        "shovelAsset": "1513261860032177"
    },
    {
        "id": "shovel_creature02",
        "name": "Creature II",
        "description": "The greatest creatures of the islands will yield to you.",
        "icon": "721534950699594",
        "index": "39",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "35",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Creature",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_creature03",
        "evolutionLevel": "44",
        "baseShovel": "shovel_creature",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Creature Items.",
        "ability1AssetId": "1848598249035764",
        "shovelAsset": "1720712841961737"
    },
    {
        "id": "shovel_creature03",
        "name": "Creature III",
        "description": "The greatest creatures of the islands will yield to you.",
        "icon": "772865988733826",
        "index": "40",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "45",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Creature",
        "itemToBias": "",
        "biasWeight": "4",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_creature04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_creature",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Creature Items.",
        "ability1AssetId": "1848598249035764",
        "shovelAsset": "1133106131964511"
    },
    {
        "id": "shovel_creature04",
        "name": "Creature IV",
        "description": "The greatest creatures of the islands will yield to you.",
        "icon": "588905760710313",
        "index": "41",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Creature",
        "itemToBias": "",
        "biasWeight": "5",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_creature",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Creature Items.",
        "ability1AssetId": "1848598249035764",
        "shovelAsset": "1641972746475015"
    },
    {
        "id": "shovel_base05",
        "name": "UFO",
        "description": "This looks like it belonged to Cousin Lou.",
        "icon": "975838704132938",
        "index": "42",
        "price": "44800",
        "levelRequirement": "20",
        "defaultLevel": "20",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "16000",
        "categoryToBias": "Alien",
        "itemToBias": "",
        "biasWeight": "0",
        "rarity": "0",
        "itemCost1ID": "datachip001",
        "itemCost1Amount": "1",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_ufo02",
        "evolutionLevel": "29",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Excels at digging up Alien Items.",
        "ability1AssetId": "1152695306469795",
        "shovelAsset": "1267250541604309"
    },
    {
        "id": "shovel_ufo02",
        "name": "UFO II",
        "description": "This looks like it belonged to Cousin Lou.",
        "icon": "1028582199422339",
        "index": "43",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Alien",
        "itemToBias": "",
        "biasWeight": "1",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_ufo03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_base05",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Alien Items.",
        "ability1AssetId": "1152695306469795",
        "shovelAsset": "24324678723795359"
    },
    {
        "id": "shovel_ufo03",
        "name": "UFO III",
        "description": "This looks like it belonged to Cousin Lou.",
        "icon": "2784917465038527",
        "index": "44",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Alien",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_ufo04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_base05",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Alien Items.",
        "ability1AssetId": "1152695306469795",
        "shovelAsset": "1483984953029844"
    },
    {
        "id": "shovel_ufo04",
        "name": "UFO IV",
        "description": "This looks like it belonged to Cousin Lou.",
        "icon": "2774418082754527",
        "index": "45",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Alien",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_base05",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Alien Items.",
        "ability1AssetId": "1152695306469795",
        "shovelAsset": "1068903848290554"
    },
    {
        "id": "shovel_captain",
        "name": "Captain's",
        "description": "Passed down from Captain to Captain. It exudes a deep pirate lineage. ",
        "icon": "657752993597633",
        "index": "46",
        "price": "59400",
        "levelRequirement": "23",
        "defaultLevel": "20",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Monstrous",
        "itemToBias": "",
        "biasWeight": "0",
        "rarity": "0",
        "itemCost1ID": "strawhat001",
        "itemCost1Amount": "1",
        "itemCost2ID": "redx001",
        "itemCost2Amount": "1",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_captain02",
        "evolutionLevel": "29",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Grants the ability to dig Cthulu from Ghost Ship",
        "ability1AssetId": "1035317601261032",
        "shovelAsset": "1096948212380216"
    },
    {
        "id": "shovel_captain02",
        "name": "Captain's II",
        "description": "Passed down from Captain to Captain. It exudes a deep pirate lineage. ",
        "icon": "1426577438470776",
        "index": "47",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Monstrous",
        "itemToBias": "",
        "biasWeight": "1",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_captain03",
        "evolutionLevel": "39",
        "baseShovel": "shovel_captain",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Higher chance of digging Cthulu from Ghost Ship",
        "ability1AssetId": "1035317601261032",
        "shovelAsset": "1105168924853125"
    },
    {
        "id": "shovel_captain03",
        "name": "Captain's III",
        "description": "Passed down from Captain to Captain. It exudes a deep pirate lineage. ",
        "icon": "1124277512870436",
        "index": "48",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Monstrous",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_captain04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_captain",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greater chance of digging Cthulu from Ghost Ship",
        "ability1AssetId": "1035317601261032",
        "shovelAsset": "761983129666879"
    },
    {
        "id": "shovel_captain04",
        "name": "Captain's IV",
        "description": "Passed down from Captain to Captain. It exudes a deep pirate lineage. ",
        "icon": "618007024100679",
        "index": "49",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Monstrous",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_captain",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massive chance of digging Cthulu from Ghost Ship",
        "ability1AssetId": "1035317601261032",
        "shovelAsset": "1295901195504700"
    },
    {
        "id": "shovel_prismatic",
        "name": "Ancient",
        "description": "Legends tell of a shovel wielded by our digging ancestors.",
        "icon": "1800726437322086",
        "index": "50",
        "price": "144400",
        "levelRequirement": "44",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Ancient",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "ancientshovelhandle001",
        "itemCost1Amount": "1",
        "itemCost2ID": "ancientshovelblade001",
        "itemCost2Amount": "1",
        "itemCost3ID": "ancientshovelpole001",
        "itemCost3Amount": "1",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Grants the ability to perform interplanetary digs.",
        "ability1AssetId": "1227152602536109",
        "shovelAsset": "1252823729926015"
    },
    {
        "id": "shovel_final",
        "name": "Final",
        "description": "The royal family's most prized posession.",
        "icon": "1109224034403425",
        "index": "51",
        "price": "177700",
        "levelRequirement": "50",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Final",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "temporaldrake001",
        "itemCost1Amount": "1",
        "itemCost2ID": "northstar001",
        "itemCost2Amount": "1",
        "itemCost3ID": "cthulu001",
        "itemCost3Amount": "1",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Grants the ability to perform The Final Dig. ",
        "ability1AssetId": "1227152602536109",
        "shovelAsset": "785443630578203"
    },
    {
        "id": "shovel_beans",
        "name": "Beanstalk",
        "description": "Thanks for playing Shovel Up! Early Access!",
        "icon": "530461276202438",
        "index": "52",
        "price": "150",
        "levelRequirement": "2",
        "defaultLevel": "1",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_beans02",
        "evolutionLevel": "3",
        "baseShovel": "",
        "ability1Type": "itemWeight",
        "ability1MinValue": "6",
        "ability1MaxValue": "6",
        "ability1Key": "",
        "ability1Chance": "0.1",
        "ability1Description": "10% chance to dig up items that are 6x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "4303100736680435"
    },
    {
        "id": "shovel_beans02",
        "name": "Beanstalk II",
        "description": "Thanks for playing Shovel Up! Early Access!",
        "icon": "1730049727622346",
        "index": "53",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "4",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_beans03",
        "evolutionLevel": "14",
        "baseShovel": "shovel_beans",
        "ability1Type": "itemWeight",
        "ability1MinValue": "6",
        "ability1MaxValue": "6",
        "ability1Key": "",
        "ability1Chance": "0.2",
        "ability1Description": "20% chance to dig up items that are 6x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "765450822639616"
    },
    {
        "id": "shovel_beans03",
        "name": "Beanstalk III",
        "description": "Thanks for playing Shovel Up! Early Access!",
        "icon": "728022336628736",
        "index": "54",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "15",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_beans04",
        "evolutionLevel": "29",
        "baseShovel": "shovel_beans",
        "ability1Type": "itemWeight",
        "ability1MinValue": "6",
        "ability1MaxValue": "6",
        "ability1Key": "",
        "ability1Chance": "0.25",
        "ability1Description": "25% chance to dig up items that are 6x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "1451910322786472"
    },
    {
        "id": "shovel_beans04",
        "name": "Beanstalk IV",
        "description": "Thanks for playing Shovel Up! Early Access!",
        "icon": "702285882604866",
        "index": "55",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "",
        "itemToBias": "",
        "biasWeight": "",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_beans",
        "ability1Type": "itemWeight",
        "ability1MinValue": "6",
        "ability1MaxValue": "6",
        "ability1Key": "",
        "ability1Chance": "0.35",
        "ability1Description": "35% chance to dig up items that are 6x bigger.",
        "ability1AssetId": "3406999362767196",
        "shovelAsset": "1680262942646611"
    },
    {
        "id": "shovel_icequeen",
        "name": "Ice Queen's",
        "description": "The Queen's frigid armament. It's seen many battles around giant towers.",
        "icon": "1178388550968172",
        "index": "56",
        "price": "78800",
        "levelRequirement": "30",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IceQueen",
        "itemToBias": "",
        "biasWeight": "0",
        "rarity": "0",
        "itemCost1ID": "frozenlocket001",
        "itemCost1Amount": "1",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icequeen02",
        "evolutionLevel": "39",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Grants the ability to dig The North Star from her Blizzard.",
        "ability1AssetId": "24190153403909675",
        "shovelAsset": "741332495491352"
    },
    {
        "id": "shovel_icequeen02",
        "name": "Ice Queen's II",
        "description": "The Queen's frigid armament. It's seen many battles around giant towers.",
        "icon": "1045118511169786",
        "index": "57",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IceQueen",
        "itemToBias": "",
        "biasWeight": "1",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icequeen03",
        "evolutionLevel": "44",
        "baseShovel": "shovel_icequeen",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Higher chance of digging The North Star from her Blizzard.",
        "ability1AssetId": "24190153403909675",
        "shovelAsset": "1263453544688792"
    },
    {
        "id": "shovel_icequeen03",
        "name": "Ice Queen's III",
        "description": "The Queen's frigid armament. It's seen many battles around giant towers.",
        "icon": "1749827925674459",
        "index": "58",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "45",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IceQueen",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_icequeen04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_icequeen",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greater chance of digging The North Star from her Blizzard.",
        "ability1AssetId": "24190153403909675",
        "shovelAsset": "753630857317236"
    },
    {
        "id": "shovel_icequeen04",
        "name": "Ice Queen's IV",
        "description": "The Queen's frigid armament. It's seen many battles around giant towers.",
        "icon": "1831181431115436",
        "index": "59",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "IceQueen",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_icequeen",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massive chance of digging The North Star from her Blizzard.",
        "ability1AssetId": "24190153403909675",
        "shovelAsset": "1439279387109819"
    },
    {
        "id": "shovel_divine",
        "name": "Divine",
        "description": "This shovel can stand toe-to-toe with the world's most legendary weapons.",
        "icon": "596349203225076",
        "index": "60",
        "price": "99000",
        "levelRequirement": "40",
        "defaultLevel": "30",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Divine",
        "itemToBias": "",
        "biasWeight": "0",
        "rarity": "0",
        "itemCost1ID": "skyforgestaff001",
        "itemCost1Amount": "1",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_divine02",
        "evolutionLevel": "39",
        "baseShovel": "",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Allows discovery of Divine Items.",
        "ability1AssetId": "708462688641966",
        "shovelAsset": "1045455451090330"
    },
    {
        "id": "shovel_divine02",
        "name": "Divine II",
        "description": "This shovel can stand toe-to-toe with the world's most legendary weapons.",
        "icon": "1744482469484507",
        "index": "61",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "40",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Divine",
        "itemToBias": "",
        "biasWeight": "1",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_divine03",
        "evolutionLevel": "44",
        "baseShovel": "shovel_divine",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Increases chances of discovering Divine Items.",
        "ability1AssetId": "708462688641966",
        "shovelAsset": "1031086158879675"
    },
    {
        "id": "shovel_divine03",
        "name": "Divine III",
        "description": "This shovel can stand toe-to-toe with the world's most legendary weapons.",
        "icon": "716149101167382",
        "index": "62",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "45",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Divine",
        "itemToBias": "",
        "biasWeight": "2",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "shovel_divine04",
        "evolutionLevel": "49",
        "baseShovel": "shovel_divine",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Greatly increases chances of discovering Divine Items.",
        "ability1AssetId": "708462688641966",
        "shovelAsset": "1400555691384063"
    },
    {
        "id": "shovel_divine04",
        "name": "Divine IV",
        "description": "This shovel can stand toe-to-toe with the world's most legendary weapons.",
        "icon": "1439595010547915",
        "index": "63",
        "price": "",
        "levelRequirement": "",
        "defaultLevel": "50",
        "strength": "40",
        "staminaLoss": "10",
        "luck": "0",
        "precision": "0",
        "control": "0",
        "stability": "0",
        "focus": "0",
        "maxKg": "21000",
        "categoryToBias": "Divine",
        "itemToBias": "",
        "biasWeight": "3",
        "rarity": "0",
        "itemCost1ID": "",
        "itemCost1Amount": "",
        "itemCost2ID": "",
        "itemCost2Amount": "",
        "itemCost3ID": "",
        "itemCost3Amount": "",
        "evolution": "",
        "evolutionLevel": "",
        "baseShovel": "shovel_divine",
        "ability1Type": "",
        "ability1MinValue": "",
        "ability1MaxValue": "",
        "ability1Key": "",
        "ability1Chance": "",
        "ability1Description": "Massively increases chances of discovering Divine Items.",
        "ability1AssetId": "708462688641966",
        "shovelAsset": "24087849394189831"
    }
]
    `;
}
